mkdir -p build
cd build

#INSTALL_DIR=../../../cppbuild/linux-x86_64
#INSTALL_DIR_ABSOLUTE="$(dirname $(readlink -e $INSTALL_DIR))/$(basename $INSTALL_DIR)"

#echo $INSTALL_DIR_ABSOLUTE

#CGAL_DIR="$INSTALL_DIR_ABSOLUTE/lib/CGAL"
#SFCGAL_DIR="$INSTALL_DIR_ABSOLUTE"
#CGAL_CORE_PACKAGE_DIR=$INSTALL_DIR_ABSOLUTE
#STXXL_DIR_SEARCH=$INSTALL_DIR_ABSOLUTE
#BOOST_ROOT=$INSTALL_DIR_ABSOLUTE

#cmake -DCGAL_DIR=$CGAL_DIR -DSFCGAL_DIR=$SFCGAL_DIR -DSTXXL_DIR_SEARCH=$STXXL_DIR_SEARCH -DBOOST_ROOT=$BOOST_ROOT ..

cmake ..

make